package mixit.routes

/**
 * Each element has
 * - a mustache template
 * - a title
 * - several images
 */
enum class MustacheTemplate(val template: String, val title: String?) {
    About("about", "about.title"),
    Accessibility("accessibility", "accessibility.title"),
    Admin("admin", "admin.title"),
    AdminBlog("admin-blog", "admin.title"),
    AdminCache("admin-cache", "admin.cache.title"),
    AdminEvent("admin-event", "admin.title"),
    AdminEventOrganization("admin-event-organization", "admin.title"),
    AdminEventSponsor("admin-event-sponsor", "admin.title"),
    AdminEventVolunteer("admin-event-voluhteer", "admin.title"),
    AdminEvents("admin-events", "admin.events.title"),
    AdminLottery("admin-lottery", "admin.ticketing.title"),
    // AdminMailing("admin-mailing", "mailinglist.title"),
    AdminMailingConfirmation("admin-mailing-confirmation", "mailinglist.title"),
    AdminMailingEdit("admin-mailing-edit", "mailinglist.title"),
    AdminMailingList("admin-mailing-list", "mailinglist.title"),
    AdminMixetteDonation("admin-mixette-donation", "admin.donations.title"),
    AdminMixetteDonor("admin-mixette-donor", "admin.donations.title"),
    AdminMixetteDonors("admin-mixette-donors", "admin.donations.title"),
    AdminMixetteOrganization("admin-mixette-organization", "admin.donations.title"),
    AdminMixetteOrganizations("admin-mixette-organizations", "admin.donations.title"),
    AdminPost("admin-post", null),
    AdminTalk("admin-talk", "admin.talk.title"),
    AdminTalks("admin-talks", "admin.talks.title"),
    AdminTicket("admin-ticket", "admin.ticket.title"),
    // AdminTicketEdit("admin-ticket-edit", "admin.ticket.title"),
    AdminTicketPrint("admin-ticket-print", "admin.ticket.title"),
    AdminUser("admin-user", "admin.users.title"),
    AdminUsers("admin-users", "admin.users.title"),
    Blog("blog", "blog.title"),
    BlogPost("post", null),
    CodeOfConduct("code-of-conduct", "code-of-conduct.title"),
    Come("come", "come.title"),
    Faq("faq", "faq.title"),
    Home("home", null),
    EmailMailing("email-mailing", null),
    FeedbackWall("talks-feedback-wall", null),
    Login("login", null),
    LoginError("login-error", null),
    LoginConfirmation("login-confirmation", null),
    LoginCreation("login-creation", null),
    LotterySubmission("lottery-submission", null),
    LotteryEdit("lottery", "ticketing.title"),
    LotteryClosed("lottery-closed", "ticketing.title"),
    LotteryError("lottery-error", "ticketing.title"),
    Media("medias", "medias.title.html"),
    MixetteDashboard("mixette-dashboard", "mixette.dashboard.title"),
    Mixteen("mixteen", "mixteen.title"),
    Schedule("schedule", "schedule.title"),
    Search("search", "search.title"),
    Speaker("speaker", "speaker.title"),
    Sponsors("sponsors", null),
    TalkList("talks", "talks.title.html"),
    TalkDetail("talk", "talks.title.html"),
    TalkEdit("talk-edit", "talks.title.html"),
    TicketError("ticket-error", "admin.ticket.title"),
    User("user", null),
    UserEdit("user-edit", null)
}
