package mixit.ticket.model

enum class TicketType {
    SPEAKER,
    SPONSOR_LANYARD,
    SPONSOR_STAND,
    SPONSOR_PARTY,
    SPONSOR_PARTNER,
    SPONSOR_MIXTEEN,
    STAFF,
    MIXTEEN,
    ATTENDEE,
    VOLUNTEER,
    GUEST,
    GUEST_ONE_TALK,
    COMPETITION_WINNER,
    FOOD,
    MEDIA,
    MIXETTE,
    SIGNES_FORMATIONS,
    METROPOLE_DE_LYON
}
